// <auto-generated />
using LokacijaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LokacijaAPI.Migrations
{
    [DbContext(typeof(LokacijaDbContext))]
    [Migration("20260405215748_InitLokacije")]
    partial class InitLokacije
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Bulevar Mihajla Pupina 10, Beograd",
                            Kapacitet = 500,
                            Naziv = "Skladište Beograd"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Bulevar Oslobođenja 45, Novi Sad",
                            Kapacitet = 300,
                            Naziv = "Skladište Novi Sad"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Obrenovićeva 22, Niš",
                            Kapacitet = 200,
                            Naziv = "Skladište Niš"
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "Kralja Petra I 8, Kragujevac",
                            Kapacitet = 150,
                            Naziv = "Skladište Kragujevac"
                        },
                        new
                        {
                            Id = 5,
                            Adresa = "Korzo 3, Subotica",
                            Kapacitet = 250,
                            Naziv = "Skladište Subotica"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
