// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizatorAPI.Data;

#nullable disable

namespace OrganizatorAPI.Migrations
{
    [DbContext(typeof(OrganizatorDbContext))]
    partial class OrganizatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizatorAPI.Models.Organizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marko.petrovic@email.com",
                            Ime = "Marko",
                            Password = "password123",
                            Prezime = "Petrović"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ana.jovanovic@email.com",
                            Ime = "Ana",
                            Password = "password123",
                            Prezime = "Jovanović"
                        },
                        new
                        {
                            Id = 3,
                            Email = "stefan.nikolic@email.com",
                            Ime = "Stefan",
                            Password = "password123",
                            Prezime = "Nikolić"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
