// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosetilacAPI.Data;

#nullable disable

namespace PosetilacAPI.Migrations
{
    [DbContext(typeof(PosetilacDbContext))]
    [Migration("20260510101253_added-correlationid-field")]
    partial class addedcorrelationidfield
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosetilacAPI.Models.Posetilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interesovanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusZaposlenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posetilac");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrelationId = new Guid("d95a2dc4-fda5-4a8b-9e1d-55704f99bbe9"),
                            DogadjajId = 1,
                            Ime = "Petar",
                            Interesovanje = "Vestacka Inteligencija",
                            Prezime = "Ilić",
                            StatusZaposlenja = "Zaposlen"
                        },
                        new
                        {
                            Id = 2,
                            CorrelationId = new Guid("1c4b43e9-683e-4b05-a517-a9f420839479"),
                            DogadjajId = 2,
                            Ime = "Milica",
                            Interesovanje = "Web development",
                            Prezime = "Stanković",
                            StatusZaposlenja = "Student"
                        },
                        new
                        {
                            Id = 3,
                            CorrelationId = new Guid("3cb49b18-df27-4a66-ad21-87e8cf7b054e"),
                            DogadjajId = 3,
                            Ime = "Jovan",
                            Interesovanje = "Machine Learning",
                            Prezime = "Marković",
                            StatusZaposlenja = "Nezaposlen"
                        },
                        new
                        {
                            Id = 4,
                            CorrelationId = new Guid("daa8e113-960c-4c1d-addc-2b4f396895b1"),
                            DogadjajId = 1,
                            Ime = "Ana",
                            Interesovanje = "Embedded",
                            Prezime = "Pavlović",
                            StatusZaposlenja = "Stalni radni odnos"
                        },
                        new
                        {
                            Id = 5,
                            CorrelationId = new Guid("f492bd80-4540-4d04-b85c-40b1234f1fec"),
                            DogadjajId = 2,
                            Ime = "Nikola",
                            Interesovanje = "Mikroservisi",
                            Prezime = "Savić",
                            StatusZaposlenja = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
