// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosetilacAPI.Data;

#nullable disable

namespace PosetilacAPI.Migrations
{
    [DbContext(typeof(PosetilacDbContext))]
    [Migration("20260513191709_Added-OutboxState")]
    partial class AddedOutboxState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosetilacAPI.Models.Posetilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interesovanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusZaposlenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posetilac");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrelationId = new Guid("c5db59d7-9e3d-48fd-89c5-e433b5eaf01a"),
                            DogadjajId = 1,
                            Ime = "Petar",
                            Interesovanje = "Vestacka Inteligencija",
                            Prezime = "Ilić",
                            StatusZaposlenja = "Zaposlen"
                        },
                        new
                        {
                            Id = 2,
                            CorrelationId = new Guid("98230c8d-f5db-4202-9734-3385e7d11c1f"),
                            DogadjajId = 2,
                            Ime = "Milica",
                            Interesovanje = "Web development",
                            Prezime = "Stanković",
                            StatusZaposlenja = "Student"
                        },
                        new
                        {
                            Id = 3,
                            CorrelationId = new Guid("945a2aea-0eca-4322-936c-0608b7142372"),
                            DogadjajId = 3,
                            Ime = "Jovan",
                            Interesovanje = "Machine Learning",
                            Prezime = "Marković",
                            StatusZaposlenja = "Nezaposlen"
                        },
                        new
                        {
                            Id = 4,
                            CorrelationId = new Guid("9fa651d7-3dce-4c73-aa03-b0eca675b7de"),
                            DogadjajId = 1,
                            Ime = "Ana",
                            Interesovanje = "Embedded",
                            Prezime = "Pavlović",
                            StatusZaposlenja = "Stalni radni odnos"
                        },
                        new
                        {
                            Id = 5,
                            CorrelationId = new Guid("29dfd66c-644f-409e-8b2b-1dfc4a0cb386"),
                            DogadjajId = 2,
                            Ime = "Nikola",
                            Interesovanje = "Mikroservisi",
                            Prezime = "Savić",
                            StatusZaposlenja = "Student"
                        });
                });

            modelBuilder.Entity("PosetilacAPI.Models.SagaResultOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FinalState")
                        .HasColumnType("int");

                    b.Property<int>("OutboxState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SagaResultOutbox");
                });
#pragma warning restore 612, 618
        }
    }
}
