// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosetilacAPI.Data;

#nullable disable

namespace PosetilacAPI.Migrations
{
    [DbContext(typeof(PosetilacDbContext))]
    [Migration("20260509230032_Posetilac-InitialCreate")]
    partial class PosetilacInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosetilacAPI.Models.Posetilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posetilac");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ime = "Petar",
                            Prezime = "Ilić"
                        },
                        new
                        {
                            Id = 2,
                            Ime = "Milica",
                            Prezime = "Stanković"
                        },
                        new
                        {
                            Id = 3,
                            Ime = "Jovan",
                            Prezime = "Marković"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
