// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosetilacAPI.Data;

#nullable disable

namespace PosetilacAPI.Migrations
{
    [DbContext(typeof(PosetilacDbContext))]
    [Migration("20260509231439_Posetilac-AddFields")]
    partial class PosetilacAddFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosetilacAPI.Models.Posetilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interesovanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusZaposlenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posetilac");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DogadjajId = 1,
                            Ime = "Petar",
                            Interesovanje = "Vestacka Inteligencija",
                            Prezime = "Ilić",
                            StatusZaposlenja = "stalnom radnom odnosu"
                        },
                        new
                        {
                            Id = 2,
                            DogadjajId = 2,
                            Ime = "Milica",
                            Interesovanje = "Web development",
                            Prezime = "Stanković",
                            StatusZaposlenja = "student"
                        },
                        new
                        {
                            Id = 3,
                            DogadjajId = 3,
                            Ime = "Jovan",
                            Interesovanje = "Machine Learning",
                            Prezime = "Marković",
                            StatusZaposlenja = "nezaposlen"
                        },
                        new
                        {
                            Id = 4,
                            DogadjajId = 1,
                            Ime = "Ana",
                            Interesovanje = "Embedded",
                            Prezime = "Pavlović",
                            StatusZaposlenja = "stalnom radnom odnosu"
                        },
                        new
                        {
                            Id = 5,
                            DogadjajId = 2,
                            Ime = "Nikola",
                            Interesovanje = "Cloud computing",
                            Prezime = "Savić",
                            StatusZaposlenja = "student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
