// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mikroservisnaApp.Data;

#nullable disable

namespace mikroservisnaApp.Migrations
{
    [DbContext(typeof(DogadjajiDbContext))]
    partial class DogadjajiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mikroservisnaApp.Models.DogadjajPredavac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RasporedPredavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("StrucniDogadajId")
                        .HasColumnType("int");

                    b.Property<int>("StrucniDogadjajId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredavacId");

                    b.HasIndex("StrucniDogadjajId");

                    b.ToTable("Dogadjaj_Predavac");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lokacija");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Organizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizator");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Predavac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblastStrucnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Predavac");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.StrucniDogadjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("datetime2");

                    b.Property<int>("LokacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("int");

                    b.Property<int>("TipId")
                        .HasColumnType("int");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("OrganizatorId");

                    b.HasIndex("TipId");

                    b.ToTable("Dogadjaj");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.TipDogadjaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipDogadjaja");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.DogadjajPredavac", b =>
                {
                    b.HasOne("mikroservisnaApp.Models.Predavac", "Predavac")
                        .WithMany("DogadjajPredavac")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mikroservisnaApp.Models.StrucniDogadjaj", "StrucniDogadjaj")
                        .WithMany("SpisakPredavaca")
                        .HasForeignKey("StrucniDogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavac");

                    b.Navigation("StrucniDogadjaj");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.StrucniDogadjaj", b =>
                {
                    b.HasOne("mikroservisnaApp.Models.Lokacija", "Lokacija")
                        .WithMany("ListaDogadjaja")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mikroservisnaApp.Models.Organizator", "Organizator")
                        .WithMany("ListaDogadjaja")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mikroservisnaApp.Models.TipDogadjaja", "Tip")
                        .WithMany("ListaDogadjaja")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("Organizator");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Lokacija", b =>
                {
                    b.Navigation("ListaDogadjaja");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Organizator", b =>
                {
                    b.Navigation("ListaDogadjaja");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.Predavac", b =>
                {
                    b.Navigation("DogadjajPredavac");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.StrucniDogadjaj", b =>
                {
                    b.Navigation("SpisakPredavaca");
                });

            modelBuilder.Entity("mikroservisnaApp.Models.TipDogadjaja", b =>
                {
                    b.Navigation("ListaDogadjaja");
                });
#pragma warning restore 612, 618
        }
    }
}
